client_config_backend: settings
client_config:
  client_id: 885058362405-3d5ievibmuhdpecig98gbrain81vpmka.apps.googleusercontent.com
  client_secret: 0EjH0NfevIS84b9GnNFnnGL9

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install